export interface ViewOrders{
    NumPed: number;
    Serie: string;
    Fecha: string;
    FechaEntrega: string;
    CodComercial: number;
    Comercial: String;
    CodCli: number;
    NombreCliente: String;
    DenominacionComercial: String;
    Destino: string;
    Direccion: string;
    Localidad: string;
    CodPostal: string;
    Provincia: string;
    Total: number;
    Pagado: number;
    Pendiente: number;
    CodFormaPago: number;
    DescripcionFormaPago: string;
    CodigoEstado: number;
    Estado: string;
    PorcComision: number;
    SerieFra: string;
    NumFra: number;
    FechaFra: string;
    CodDestino: number;    
    DtoPP: number;
}